doctrine:
  dbal:
    types:
      game_object: PennyPHP\Core\Doctrine\Type\GameObjectType
  orm:
    mappings:
      CoreBundle:
        type: attribute
        is_bundle: true
        dir: '/src/Entity'
        prefix: 'PennyPHP\Core\Entity'
        alias: PennyPHP\Core