services:
  _defaults:
    autowire: true
    autoconfigure: true

  PennyPHP\Core\:
    resource: '../src/'
    exclude:
      - '../src/GameObject/Entity'
      - '../src/GameObject/Event'
      - '../src/GameObject/Exception'
      - '../src/GameComponent/Entity'
      - '../src/GameComponent/Exception'